spring.application.name=api
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/ticketflow?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=${DB_DRIVER:com.mysql.cj.jdbc.Driver}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
payment.mercadopago.api-url=${MP_API_URL:https://api.mercadopago.com}
payment.mercadopago.access-token=${MP_ACCESS_TOKEN:}
payment.mercadopago.webhook-secret=${MP_WEBHOOK_SECRET:}
payment.mercadopago.notification-url=${MP_NOTIFICATION_URL:}
payment.mercadopago.frontend-url=${FRONTEND_URL:http://localhost:4200}
payment.mercadopago.sandbox=${MP_SANDBOX:true}
